import React from "react";
import Form from "../../forms/components/Form";
import Input from "../../forms/components/Input";


export default function CardForm({
    onSubmit,
    onReset,
    isFormValid,
    title,
    errors,
    data,
    onInputChange,
}) {
    return (
        <Form
            onSubmit={onSubmit}
            onReset={onReset}
            isFormValid={isFormValid}
            title={title}
            styles={{ maxWidth: "800px" }}
        >
            <Input
                name="title"
                label="title"
                error={errors.title}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="subtitle"
                label="subtitle"
                error={errors.subtitle}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="description"
                label="description"
                error={errors.description}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="phone"
                label="phone"
                type="phone"
                error={errors.phone}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="email"
                label="email"
                type="email"
                error={errors.email}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="web"
                label="web"
                error={errors.web}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                name="url"
                label="image url"
                error={errors.url}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                name="alt"
                label="image alt"
                error={errors.alt}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                name="state"
                label="state"
                error={errors.state}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
            <Input
                label="country"
                name="country"
                error={errors.country}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="city"
                label="city"
                error={errors.city}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="street"
                label="street"
                error={errors.street}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="houseNumber"
                label="house Number"
                type="number"
                error={errors.houseNumber}
                onChange={onInputChange}
                data={data}
                sm={6}
            />
            <Input
                name="zip"
                label="zip"
                error={errors.zip}
                onChange={onInputChange}
                data={data}
                sm={6}
                required={false}
            />
        </Form>
    );
}
